/**
 * @rustrak/client - TypeScript client for Rustrak API
 *
 * A type-safe, fully-featured client for interacting with Rustrak error tracking API.
 *
 * @packageDocumentation
 */

// Main client
export { RustrakClient } from './client.js';

// Configuration
export type { ClientConfig } from './config.js';
// Errors: one closed union, keyed on `kind`, replacing the nine classes.
export {
  FIELD_ERROR_CODES,
  type FieldError,
  type FieldErrorCode,
  isRetryable,
  NETWORK_ERROR_MESSAGE,
  type RustrakError,
  type RustrakErrorKind,
  SERVER_ERROR_MESSAGE,
  TIMEOUT_ERROR_MESSAGE,
} from './errors.js';
// Result: every resource method returns one of these.
export {
  Err,
  mapResult,
  Ok,
  type Result,
  unwrap,
  unwrapOr,
} from './result.js';
// Types
export type {
  AgentModelRow,
  AgentSummary,
  AgentToolRow,
  AcceptInvitation,
  ActivityEntry,
  AgentBreakdownOptions,
  AgentDurationPoint,
  AgentTimeseriesOptions,
  AgentTimeseriesPoint,
  AgentTraceSummary,
  AgentTracesOptions,
  AlertHistory,
  AlertIntegration,
  AlertRule,
  AlertRuleChannelInput,
  AlertStatus,
  AlertType,
  ApiError,
  AssembleInput,
  AssembleResponse,
  AuthResponse,
  AuthToken,
  AuthTokenCreated,
  BulkDeleteIssues,
  BulkUpdateIssues,
  ChunkUploadCapability,
  CleanupCounts,
  CleanupOptions,
  CreateAlertIntegration,
  CreateAlertRule,
  CreateAuthToken,
  CreateComment,
  CreateInvitation,
  CreateProject,
  CreateUserReport,
  Event,
  EventDetail,
  EventTimeseries,
  EventTimeseriesPoint,
  GenAiBreakdownRow,
  GlobalRole,
  Invitation,
  InvitationInfo,
  Issue,
  IssueAggregates,
  IssueFilter,
  IssueHash,
  IssuePriority,
  IssueSort,
  IssueStats,
  IssueStatsWindow,
  IssueStatus,
  IssueTagValue,
  ListAlertHistoryOptions,
  ListEventsOptions,
  ListIssuesOptions,
  ListLogsOptions,
  ListProjectsOptions,
  ListSourceMapsResponse,
  ListSpansOptions,
  ListTransactionsOptions,
  Log,
  LoginRequest,
  LoginResult,
  MetricDelta,
  OffsetPaginatedResponse,
  PaginatedResponse,
  Project,
  ProjectListStats,
  ProjectMember,
  ProjectRole,
  ProjectStatsSummary,
  ProjectStorage,
  ProviderType,
  RateLimits,
  RegisterRequest,
  ReleaseHealthRow,
  ReleaseHealthStatsOptions,
  RoutingOverride,
  ServerVersion,
  SessionSummary,
  SessionTimeseries,
  SessionTimeseriesPoint,
  SortOrder,
  SourceMapFile,
  SourceMapGcResult,
  SourceMapStorage,
  Span,
  SpanDetail,
  StorageSummary,
  TagSummary,
  TagValueCount,
  TeamMember,
  PreviewTemplateResponse,
  TestChannelResponse,
  TestIntegrationBody,
  Transaction,
  TransactionDetail,
  TransactionStats,
  UpdateAlertIntegration,
  UpdateAlertRule,
  UpdateIssueState,
  UpdateProject,
  UpdateUserRole,
  UpsertProjectMember,
  User,
  UserReport,
} from './types/index.js';
